//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcroPad.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AcroPad.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap ActivateNext {
            get {
                object obj = ResourceManager.GetObject("ActivateNext", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap ActivatePrev {
            get {
                object obj = ResourceManager.GetObject("ActivatePrev", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Add {
            get {
                object obj = ResourceManager.GetObject("Add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap AddWindow {
            get {
                object obj = ResourceManager.GetObject("AddWindow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Clean {
            get {
                object obj = ResourceManager.GetObject("Clean", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Close {
            get {
                object obj = ResourceManager.GetObject("Close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap CloseAll {
            get {
                object obj = ResourceManager.GetObject("CloseAll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   AppData に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CNS_DIR_DATA {
            get {
                return ResourceManager.GetString("CNS_DIR_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Log に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CNS_DIR_LOG {
            get {
                return ResourceManager.GetString("CNS_DIR_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   History.xml に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CNS_FIL_HISTORY {
            get {
                return ResourceManager.GetString("CNS_FIL_HISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language.xml に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CNS_FIL_LANGUAGE {
            get {
                return ResourceManager.GetString("CNS_FIL_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Layout.xml に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CNS_FIL_LAYOUT {
            get {
                return ResourceManager.GetString("CNS_FIL_LAYOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting.xml に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CNS_FIL_SETTING {
            get {
                return ResourceManager.GetString("CNS_FIL_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すべてのファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CNS_STR_ALL_FILE_TYPE {
            get {
                return ResourceManager.GetString("CNS_STR_ALL_FILE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自動識別 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CNS_STR_AUTOMATIC_IDENTIFIER {
            get {
                return ResourceManager.GetString("CNS_STR_AUTOMATIC_IDENTIFIER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Copy {
            get {
                object obj = ResourceManager.GetObject("Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Cut {
            get {
                object obj = ResourceManager.GetObject("Cut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Delete {
            get {
                object obj = ResourceManager.GetObject("Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon EditorDocument {
            get {
                object obj = ResourceManager.GetObject("EditorDocument", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Exit {
            get {
                object obj = ResourceManager.GetObject("Exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Explorer {
            get {
                object obj = ResourceManager.GetObject("Explorer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon ExplorerContent {
            get {
                object obj = ResourceManager.GetObject("ExplorerContent", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Find {
            get {
                object obj = ResourceManager.GetObject("Find", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap FindNext {
            get {
                object obj = ResourceManager.GetObject("FindNext", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap FindPrev {
            get {
                object obj = ResourceManager.GetObject("FindPrev", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap GoToLine {
            get {
                object obj = ResourceManager.GetObject("GoToLine", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap GoToMatchedBracket {
            get {
                object obj = ResourceManager.GetObject("GoToMatchedBracket", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Information {
            get {
                object obj = ResourceManager.GetObject("Information", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon MainForm {
            get {
                object obj = ResourceManager.GetObject("MainForm", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap MenuBar {
            get {
                object obj = ResourceManager.GetObject("MenuBar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   {0} を異なる文字コードで再読み込みします。
        ///
        ///  使用されていた文字コード: {1}
        ///  新たに指定された文字コード: {2}
        ///
        ///よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_CFM_RELOAD {
            get {
                return ResourceManager.GetString("MSG_CFM_RELOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} への変更内容を保存しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_CFM_SAVE_CHANGES {
            get {
                return ResourceManager.GetString("MSG_CFM_SAVE_CHANGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正規表現の解析に失敗しました。
        ///入力に誤りがある可能性があります。
        ///
        ///メッセージ:
        ///  {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_ERR_REGEX_FAILED {
            get {
                return ResourceManager.GetString("MSG_ERR_REGEX_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   読み取り専用のファイルは上書き保存できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_ERR_SAVE_FAILED_BY_READ_ONLY {
            get {
                return ResourceManager.GetString("MSG_ERR_SAVE_FAILED_BY_READ_ONLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索する文字列を入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_INF_NOT_ENTERED {
            get {
                return ResourceManager.GetString("MSG_INF_NOT_ENTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定された文字列は見つかりませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_INF_NOT_FOUND {
            get {
                return ResourceManager.GetString("MSG_INF_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} 箇所を置き換えました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_INF_REPLACE_ALL {
            get {
                return ResourceManager.GetString("MSG_INF_REPLACE_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   置換の履歴をクリアします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_WAR_CLEAR_REPLACE_HISTORY {
            get {
                return ResourceManager.GetString("MSG_WAR_CLEAR_REPLACE_HISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索の履歴をクリアします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_WAR_CLEAR_SEARCH_HISTORY {
            get {
                return ResourceManager.GetString("MSG_WAR_CLEAR_SEARCH_HISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} への変更内容は破棄されます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_WAR_DISPOSE_CHANGE {
            get {
                return ResourceManager.GetString("MSG_WAR_DISPOSE_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}
        ///は他のプロセスによって書き込みが禁止されています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_WAR_WRITE_INHIBIT {
            get {
                return ResourceManager.GetString("MSG_WAR_WRITE_INHIBIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap OpenFolder {
            get {
                object obj = ResourceManager.GetObject("OpenFolder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap OpenIn {
            get {
                object obj = ResourceManager.GetObject("OpenIn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Option {
            get {
                object obj = ResourceManager.GetObject("Option", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Paste {
            get {
                object obj = ResourceManager.GetObject("Paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap PrintOut {
            get {
                object obj = ResourceManager.GetObject("PrintOut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap PrintPreview {
            get {
                object obj = ResourceManager.GetObject("PrintPreview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Property {
            get {
                object obj = ResourceManager.GetObject("Property", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Redo {
            get {
                object obj = ResourceManager.GetObject("Redo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Rename {
            get {
                object obj = ResourceManager.GetObject("Rename", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Replace {
            get {
                object obj = ResourceManager.GetObject("Replace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Save {
            get {
                object obj = ResourceManager.GetObject("Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap SaveAll {
            get {
                object obj = ResourceManager.GetObject("SaveAll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap SaveAs {
            get {
                object obj = ResourceManager.GetObject("SaveAs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon SearchContent {
            get {
                object obj = ResourceManager.GetObject("SearchContent", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap SelectAll {
            get {
                object obj = ResourceManager.GetObject("SelectAll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap StatusBar {
            get {
                object obj = ResourceManager.GetObject("StatusBar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap ToolBar {
            get {
                object obj = ResourceManager.GetObject("ToolBar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap TopMost {
            get {
                object obj = ResourceManager.GetObject("TopMost", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Undo {
            get {
                object obj = ResourceManager.GetObject("Undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   using static System.Console;
        ///public class Program
        ///{
        ///    /// &lt;summary&gt;
        ///    /// アプリケーションのメインエントリポイントです。
        ///    /// &lt;/summary&gt;
        ///    public static void Main()
        ///    {
        ///        WriteLine(&quot;Hello World&quot;); // コンソールに出力する
        ///    }
        ///} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VAL_OPTION_PREVIEW {
            get {
                return ResourceManager.GetString("VAL_OPTION_PREVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap ZoomIn {
            get {
                object obj = ResourceManager.GetObject("ZoomIn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap ZoomOut {
            get {
                object obj = ResourceManager.GetObject("ZoomOut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
